// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozadplmtmuwykreoxagg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96YWRwbG10bXV3eWtyZW94YWdnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzNDcyMzQsImV4cCI6MjA2OTkyMzIzNH0.gTQWp2GrgRKBwZQ0Ro6R6mpGyGzJLL1JeQI_R0gugDE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});